name: Automatic Deployment to EC2 Instance

on:
  # TRIGGERS JOB(S) WHEN PUSHING TO MAIN OR DEV
  push:
    branches:
      - main
      - dev

jobs:
  build:
    # THE BUILD JOB WILL RUN IN AN UBUNTU MACHINE PROVIDED BY GITHUB
    runs-on: ubuntu-latest
    environment:
      # TERNARY OPERATOR TO SET ENVIRONMENT BASE ON BRANCH
      # THE VALUE OF SECRET(S) WILL DEPEND ON THE ENVIRONMENT
      name: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Development' }}
    steps:
      # CHECKOUTS TO THE ROOT DIRECTORY OF THE REPOSITORY
      - name: Checkout Source
        uses: actions/checkout@v4

      # CREATES AN .env FILE
      # SET SECRETS IN SETTINGS > SECRETS AND VARIABLES > ACTIONS
      - name: Create .env file
        run: |
          echo "PORT=${{ secrets.PORT }}" >> .env 
          echo "IS_ODD=${{ secrets.IS_ODD }}" >> .env 
          echo "IS_EVEN=${{ secrets.IS_EVEN }}" >> .env 

      - name: Read Version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t marvinraydalida/github-actions-basic-server:${{ env.VERSION }} .
          docker build -t marvinraydalida/github-actions-basic-server:latest .
          
      - name: Authenticate to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish Image to Docker Hub
        run: |
          docker push marvinraydalida/github-actions-basic-server:${{ env.VERSION }}
          docker push marvinraydalida/github-actions-basic-server:latest

  deploy-production:
    # THIS JOB WILL NOT TRIGGER UNTIL BUILD IS DONE
    needs: build
    # JOB WILL CONTINUE IF PUSHING TO MAIN BRANCH
    if: github.ref == 'refs/heads/main'
    # A SELF HOSTED RUNNER THAT MATCHES ALL LABELS WILL BE ELIGIBLE TO RUN THE JOB
    runs-on: [self-hosted, linux, X64, production]
    environment: Production
    steps:
      - name: Pull image from docker hub
      run: docker pull marvinraydalida/github-actions-basic-server:latest
      - name: Delete old container
      run: docker rm -f github-actions-basic-server-container
      - name: Create and run new docker container
      run: |
        docker run -d -p 8000:3000 --name github-actions-basic-server-container marvinraydalida/github-actions-basic-server

  deploy-development:
    # THIS JOB WILL NOT TRIGGER UNTIL BUILD IS DONE
    needs: build
    # JOB WILL CONTINUE IF PUSHING TO DEV BRANCH
    if: github.ref == 'refs/heads/dev'
    # A SELF HOSTED RUNNER THAT MATCHES ALL LABELS WILL BE ELIGIBLE TO RUN THE JOB
    runs-on: [self-hosted, linux, X64, development]
    environment: Development
    steps:
      - name: Pull image from docker hub
      run: docker pull marvinraydalida/github-actions-basic-server:latest
      - name: Delete old container
      run: docker rm -f github-actions-basic-server-container
      - name: Create and run new docker container
      run: |
        docker run -d -p 8000:3000 --name github-actions-basic-server-container marvinraydalida/github-actions-basic-server